# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
