# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20170413_1547'),
        ('properties', '0002_auto_20170413_1547'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
