# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0005_auto_20170627_2034'),
        ('user', '0004_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('userprofile', django.db.models.manager.Manager()),
            ],
        ),
    ]
