# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170712_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='investor',
            field=models.BooleanField(default=True),
        ),
    ]
