# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20170712_2132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_userprofile_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties')),
                ('realtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
