# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 21:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_directgroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('user_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
