# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=40)),
                ('coordinates', models.CharField(max_length=50)),
                ('sq_ft', models.FloatField()),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('past_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('date_upload', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
