# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170413_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_image'),
        ),
    ]
