# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20170613_2101'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='properties',
            managers=[
                ('properties', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='properties',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='properties',
            name='latitude',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='longitude',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
