# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20170627_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='prop',
            new_name='prop_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
