# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0006_auto_20170712_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='realtor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
