# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0007_properties_realtor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprop',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='userprop',
            name='user',
        ),
        migrations.AlterField(
            model_name='properties',
            name='date_upload',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='UserProp',
        ),
        migrations.AddField(
            model_name='investment',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
